doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '10.1'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\User\Domain\User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/user'
                prefix: 'App\User\Domain'
                alias: User
