doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '10.1'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        schema_filter: ~^(?!view_)~
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/user'
                prefix: 'App\User\Domain'
                alias: User
            Parking:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/parking'
                prefix: 'App\Parking\Domain'
                alias: Parking
            Shared:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/shared'
                prefix: 'App\Shared\Domain'
                alias: Shared
            Opinion:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/opinion'
                prefix: 'App\Opinion\Domain'
                alias: Opinion
            ParkingSearch:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/parking_search'
                prefix: 'App\ParkingSearch\Domain'
                alias: ParkingSearch
            Reservation:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/reservation'
                prefix: 'App\Reservation\Domain'
                alias: Reservation