App\Parking\Domain\Employee:
  type: entity
  table: employee
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    userId:
      type: string
  manyToOne:
    parking:
      targetEntity: App\Parking\Domain\Parking
      inversedBy: employees