App\Parking\Domain\Model\ParkingSpace:
  type: entity
  table: parking_space
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    count:
      type: integer
  manyToOne:
    type:
      targetEntity: App\Shared\Domain\Model\ParkingSpaceType
    parking:
      targetEntity: App\Parking\Domain\Parking
      inversedBy: parkingSpaces