App\Staying\Domain\Staying:
  type: entity
  table: staying
  id:
    id:
      type: string
      nullable: false
      length: 36
      generator: { strategy: NONE }
  fields:
    userId:
      type: string
    parkingId:
      type: string
    start:
      type: datetime
      nullable: true
    end:
      type: datetime
      nullable: true
    status:
      type: integer
  manyToOne:
    type:
      targetEntity: App\Shared\Domain\Model\ParkingSpaceType