App\Opinion\Domain\Opinion:
  type: entity
  table: opinion
  id:
    id:
      type: string
      nullable: false
      length: 36
      generator: { strategy: NONE }
  fields:
    rate:
      type: integer
    comment:
      type: string
    author:
      type: string
    parkingId:
      type: string
    created:
      type: datetime