App\ParkingSearch\Domain\ParkingView:
  type: entity
  readOnly: true
  table: view_parking
  id:
    id:
      type: string
      generator: { strategy: NONE }
  fields:
    name:
      type: string
    owner:
      type: string
    lat:
      type: string
    lng:
      type: string
    street:
      type: string
    number:
      type: string
    postCode:
      type: string
    city:
      type: string
    rate:
      type: string
    openingHours:
      type: string
    priceList:
      type: string
    parkingSpace:
      type: string